<?php

namespace common\models;

use common\helpers\ModelErrorHelper;
use Yii;
use yii\db\Exception;

/**
 * This is the model class for table "nomination".
 *
 * @property int $id
 *
 * @property CompetitionNominations[] $competitionNominations
 * @property NominationLanguage[] $nominationLanguages
 */
class Nomination extends \yii\db\ActiveRecord
{
    public $default_name = "";


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'nomination';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['default_name','string']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
        ];
    }

    /**
     * Gets query for [[CompetitionNominations]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionNominations()
    {
        return $this->hasMany(CompetitionNominations::className(), ['nomination_id' => 'id']);
    }

    /**
     * Gets query for [[NominationLanguages]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getNominationLanguages()
    {
        return $this->hasMany(NominationLanguage::className(), ['nomination_id' => 'id'])->orderBy(['language_id'=>SORT_ASC]);
    }

    public function getNominationLanguage(){
        return $this->hasOne(NominationLanguage::className(), ['nomination_id' => 'id'])
            ->onCondition(['language_id'=>Language::RUSSIAN])
            ;
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($insert) {
            $languages = Language::find()->all();
            foreach ($languages as $language) {
                $model = (new NominationLanguage([
                    'name'=>$this->default_name,
                    'nomination_id'=>$this->id,
                    'language_id'=>$language->id
                ]));
                if(!$model->save()){
                    throw new Exception(ModelErrorHelper::getModelErrorMessage($model));
                }
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
