<?php

namespace common\models;

use common\helpers\ModelErrorHelper;
use Yii;
use yii\db\Exception;

/**
 * This is the model class for table "performance_type".
 *
 * @property int $id
 *
 * @property CompetitionPerformanceTypes[] $competitionPerformanceTypes
 * @property PerformanceTypeLanguage[] $performanceTypeLanguages
 */
class PerformanceType extends \yii\db\ActiveRecord
{
    public $default_name = "";

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'performance_type';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
        ];
    }

    /**
     * Gets query for [[CompetitionPerformanceTypes]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCompetitionPerformanceTypes()
    {
        return $this->hasMany(CompetitionPerformanceTypes::className(), ['performance_type_id' => 'id']);
    }

    /**
     * Gets query for [[PerformanceTypeLanguages]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getPerformanceTypeLanguages()
    {
        return $this->hasMany(PerformanceTypeLanguage::className(), ['performance_type_id' => 'id'])->orderBy(['language_id'=>SORT_ASC]);
    }

    public function getPerformanceTypeLanguage(){
        return $this->hasOne(PerformanceTypeLanguage::className(), ['performance_type_id' => 'id'])
            ->onCondition(['language_id'=>Language::RUSSIAN])
            ;
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($insert) {
            $languages = Language::find()->all();
            foreach ($languages as $language) {
                $model = (new PerformanceTypeLanguage([
                    'name'=>$this->default_name,
                    'performance_type_id'=>$this->id,
                    'language_id'=>$language->id
                ]));
                if(!$model->save()){
                    throw new Exception(ModelErrorHelper::getModelErrorMessage($model));
                }
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
